#!/usr/bin/env python3
"""Regenerate TRACE.md: run both components' tests, map each test to the criterion ids in
its name, and list every criterion with no test.

usage: tools/trace.py --spec <path to book-manager-01/spec>
"""
import argparse, json, pathlib, re, subprocess, sys, tempfile, xml.etree.ElementTree as ET
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
AC = re.compile(r"AC-[A-Z]+-\d{3}-\d+")

# Criteria of the inherited standards. Their text is not in the spec directory; it was
# supplied with the build brief, and is reproduced in QUESTIONS.md where it matters.
STANDARD_CRITERIA = {
    "org-sec-004": ["AC-SEC-011-1", "AC-SEC-011-2", "AC-SEC-012-1", "AC-SEC-013-1"],
    "plt-ui-001": ["AC-UI-004-1", "AC-UI-004-2", "AC-UI-002-1", "AC-UI-002-2", "AC-UI-003-1", "AC-UI-003-2"],
    "plt-ui-react-001": ["AC-UIR-001-1", "AC-UIR-001-2", "AC-UIR-002-1", "AC-UIR-002-2"],
    "plt-api-001": ["AC-API-001-1", "AC-API-001-2", "AC-API-002-1", "AC-API-002-2", "AC-API-003-1", "AC-API-003-2", "AC-API-004-1", "AC-API-004-2"],
    "plt-svc-001": ["AC-SVC-001-1", "AC-SVC-001-2", "AC-SVC-002-1", "AC-SVC-002-2", "AC-SVC-003-1", "AC-SVC-003-2", "AC-SVC-004-1", "AC-SVC-004-2"],
}

# Why a criterion has no test named for it. Anything untested and not listed here is reported as a gap.
UNTESTED_REASONS = {
    "AC-SEC-012-1": "No inbound integration from an external system exists to put mutual TLS on (QUESTIONS.md Q-SEC-01).",
}
PLATFORM_CHECK = ("Describes the behaviour of the platform conformance check, which is not available to this build "
                  "(QUESTIONS.md Q-STD-02). Repository-state tests named for the requirement stand in.")


def api_results():
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(["dotnet", "test", str(ROOT / "api"), "--logger", "trx;LogFileName=r.trx",
                        "--results-directory", tmp], capture_output=True, text=True)
        trx = next(pathlib.Path(tmp).rglob("*.trx"))
        ns = {"t": "http://microsoft.com/schemas/VisualStudio/TeamTest/2010"}
        for r in ET.parse(trx).getroot().iterfind(".//t:UnitTestResult", ns):
            yield "api", re.sub(r"\(.*\)$", "", r.get("testName")), r.get("outcome") == "Passed"


def web_results():
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "r.json"
        subprocess.run(["npx", "vitest", "run", "--reporter=json", f"--outputFile={out}"],
                       cwd=ROOT / "web", capture_output=True, text=True)
        for f in json.loads(out.read_text())["testResults"]:
            for t in f["assertionResults"]:
                yield "web", t["title"], t["status"] == "passed"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", required=True, type=pathlib.Path)
    spec = parser.parse_args().spec

    system = {}
    for yaml in sorted((spec / "capabilities").glob("*.yaml")):
        text = yaml.read_text()
        code = re.search(r"^\s+code: (\w+)", text, re.M).group(1)
        system[code] = re.findall(r"- id: (AC-[A-Z]+-\d{3}-\d+)", text)

    tests = defaultdict(lambda: [0, 0])  # (component, name) -> [cases, passed]
    for component, name, passed in [*api_results(), *web_results()]:
        tests[(component, name)][0] += 1
        tests[(component, name)][1] += passed

    covered = defaultdict(list)
    rows = []
    for (component, name), (cases, passed) in sorted(tests.items(), key=lambda kv: (AC.findall(kv[0][1]) or ["~"], kv[0])):
        ids = AC.findall(name)
        for i in ids:
            covered[i].append((component, passed == cases))
        state = "pass" if passed == cases else f"**FAIL** ({cases - passed}/{cases})"
        cases_text = f" ×{cases}" if cases > 1 else ""
        rows.append(f"| {component} | {name.replace('|', '/')}{cases_text} | {', '.join(ids) or '—'} | {state} |")

    total_system = sum(len(v) for v in system.values())
    lines = ["# Traceability", "",
             "Generated by `tools/trace.py` from an actual run of both test suites. Do not edit by hand.", "",
             f"System criteria: {total_system} across {', '.join(system)}. "
             f"Tests: {len(tests)} ({sum(c for c, _ in tests.values())} cases incl. theory data rows).", "",
             "## Criteria without a passing test", ""]
    missing = []
    for code, ids in system.items():
        for i in ids:
            if not any(ok for _, ok in covered.get(i, [])):
                missing.append(f"| {i} | {code} | {'failing' if i in covered else 'no test'} |")
    lines += ["### System criteria", ""]
    lines += (["| Criterion | Capability | State |", "|---|---|---|", *missing] if missing else ["None."])
    lines += ["", "### Inherited-standard criteria", "", "| Criterion | Standard | Why |", "|---|---|---|"]
    for standard, ids in STANDARD_CRITERIA.items():
        for i in ids:
            if any(ok for _, ok in covered.get(i, [])):
                continue
            lines.append(f"| {i} | {standard} | {UNTESTED_REASONS.get(i, PLATFORM_CHECK)} |")
    lines += ["", "## Test → criterion", "",
              "Tests named for a requirement (REQ-…) rather than a criterion cover behaviour the criteria leave open; "
              "each points at the QUESTIONS.md entry that records the choice.", "",
              "| Component | Test | Criteria | Result |", "|---|---|---|---|", *rows, ""]
    (ROOT / "TRACE.md").write_text("\n".join(lines))
    failing = [r for r in rows if "FAIL" in r]
    print(f"{len(rows)} tests, {len(failing)} failing, {len(missing)} system criteria without a passing test")
    return 1 if failing else 0


if __name__ == "__main__":
    sys.exit(main())
